
export default new Map([
["src/content/articles/a-mail-server-in-a-kubernetes-cluster.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Farticles%2Fa-mail-server-in-a-kubernetes-cluster.mdx&astroContentModuleFlag=true")],
["src/content/articles/how-i-configured-my-own-home-server.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Farticles%2Fhow-i-configured-my-own-home-server.mdx&astroContentModuleFlag=true")],
["src/content/articles/how-to-avoid-too-many-a-and-aaaa-dns-records-in-your-dns-zone-file.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Farticles%2Fhow-to-avoid-too-many-a-and-aaaa-dns-records-in-your-dns-zone-file.mdx&astroContentModuleFlag=true")],
["src/content/articles/welcome.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Farticles%2Fwelcome.mdx&astroContentModuleFlag=true")],
["src/content/projects/how-i-configured-my-own-home-server.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fprojects%2Fhow-i-configured-my-own-home-server.mdx&astroContentModuleFlag=true")],
["src/content/projects/plannify.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fprojects%2Fplannify.mdx&astroContentModuleFlag=true")],
["src/content/projects/plannify copy.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fprojects%2Fplannify+copy.mdx&astroContentModuleFlag=true")],
["src/content/projects/plannify-copy.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fprojects%2Fplannify-copy.mdx&astroContentModuleFlag=true")],
["src/content/projects/plannify1.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fprojects%2Fplannify1.mdx&astroContentModuleFlag=true")],
["src/content/projects/plannify1 copy.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fprojects%2Fplannify1+copy.mdx&astroContentModuleFlag=true")],
["src/content/projects/plannify2.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fprojects%2Fplannify2.mdx&astroContentModuleFlag=true")],
["src/content/projects/beep.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fprojects%2Fbeep.mdx&astroContentModuleFlag=true")]]);
		