apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.front.name }}
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.front.replicaCount }}
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: {{ .Values.front.name }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: {{ .Values.front.name }}
    spec:
      containers:
      - name: {{ .Values.front.name }}
        image: {{ .Values.front.image }}
        imagePullPolicy: Always
        resources:
          requests:
            cpu: "4m"
            memory: "8Mi"
          limits:
            cpu: "12m"
            memory: "12Mi"
        ports: 
        - containerPort: {{ .Values.front.port }}
        startupProbe:
          httpGet:
            path: /
            port: {{ .Values.front.port }}
          failureThreshold: 30
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /
            port: {{ .Values.front.port }}
          failureThreshold: 3
          initialDelaySeconds: 10
          periodSeconds: 20
        readinessProbe:
          httpGet:
            path: /
            port: {{ .Values.front.port }}
          initialDelaySeconds: 5
          periodSeconds: 10