apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.front.name }}
  namespace: {{ .Values.namespace }}
spec:
  type: ClusterIP
  selector:
    app: {{ .Values.front.name }}
  ports:
  - port: {{ .Values.front.servicePort }}
    targetPort: {{ .Values.front.containerPort }}