apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: portfolio-dev
  namespace: argocd
spec:
  project: portfolio-dev
  source:
    repoURL: https://github.com/baptistebronsin/portfolio.git
    targetRevision: main
    path: helm
  destination:
    server: https://kubernetes.default.svc
    namespace: portfolio-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true