apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: portfolio
  namespace: argocd
spec:
  project: portfolio
  source:
    repoURL: https://gitlab.com/baptiste.bronsin/portfolio.git
    targetRevision: main
    path: helm
  destination:
    server: https://kubernetes.default.svc
    namespace: portfolio
  syncPolicy:
    automated:
      prune: true
      selfHeal: true