namespace: portfolio

front:
  name: portfolio-front
  image: registry.gitlab.com/baptiste.bronsin/portfolio:main-362d22ad
  replicaCount: 1
  port: 3000

  servicePort: 3000
  containerPort: 3000

  ingress:
    enabled: true
    annotations:
      spec.ingressClassName: traefik
      cert-manager.io/cluster-issuer: letsencrypt-prod
      traefik.ingress.kubernetes.io/router.middlewares: default-redirect-https@kubernetescrd
    hosts: baptistebronsin.be
    tls: true
    tlsSecret: portfolio-tls

